##### import libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#####  Exercise 1: From the given dataset print the first and last five rows

In [2]:
df = pd.read_csv("Automobile_data.csv")
df.head()

index      company   body-style  wheel-base  length engine-type  \
0      0  alfa-romero  convertible        88.6   168.8        dohc   
1      1  alfa-romero  convertible        88.6   168.8        dohc   
2      2  alfa-romero    hatchback        94.5   171.2        ohcv   
3      3         audi        sedan        99.8   176.6         ohc   
4      4         audi        sedan        99.4   176.6         ohc   

  num-of-cylinders  horsepower  average-mileage    price  
0             four         111               21  13495.0  
1             four         111               21  16500.0  
2              six         154               19  16500.0  
3             four         102               24  13950.0  
4             five         115               18  17450.0

In [3]:
df.tail()

index     company body-style  wheel-base  length engine-type  \
56     81  volkswagen      sedan        97.3   171.7         ohc   
57     82  volkswagen      sedan        97.3   171.7         ohc   
58     86  volkswagen      sedan        97.3   171.7         ohc   
59     87       volvo      sedan       104.3   188.8         ohc   
60     88       volvo      wagon       104.3   188.8         ohc   

   num-of-cylinders  horsepower  average-mileage    price  
56             four          85               27   7975.0  
57             four          52               37   7995.0  
58             four         100               26   9995.0  
59             four         114               23  12940.0  
60             four         114               23  13415.0

#####  Exercise 2: Clean the dataset and update the CSV file

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   index             61 non-null     int64  
 1   company           61 non-null     object 
 2   body-style        61 non-null     object 
 3   wheel-base        61 non-null     float64
 4   length            61 non-null     float64
 5   engine-type       61 non-null     object 
 6   num-of-cylinders  61 non-null     object 
 7   horsepower        61 non-null     int64  
 8   average-mileage   61 non-null     int64  
 9   price             58 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 4.9+ KB


In [44]:
for i in df.columns:
    print(i)
    print(df[i].unique())
    print("-" * 100)

index
[ 0  1  2  3  4  5  6  9 10 11 13 14 15 16 17 18 19 20 27 28 29 30 31 32
 33 34 35 36 37 38 39 43 44 45 46 47 49 50 51 52 53 54 55 56 57 61 62 63
 66 67 68 69 70 71 79 80 81 82 86 87 88]
----------------------------------------------------------------------------------------------------
company
['alfa-romero' 'audi' 'bmw' 'chevrolet' 'dodge' 'honda' 'isuzu' 'jaguar'
 'mazda' 'mercedes-benz' 'mitsubishi' 'nissan' 'porsche' 'toyota'
 'volkswagen' 'volvo']
----------------------------------------------------------------------------------------------------
body-style
['convertible' 'hatchback' 'sedan' 'wagon' 'hardtop']
----------------------------------------------------------------------------------------------------
wheel-base
[ 88.6  94.5  99.8  99.4 105.8 101.2 103.5 110.   88.4  93.7  96.5  94.3
 113.  102.   93.1  95.3 104.9 120.9 112.   96.3 100.4  89.5  98.4  95.7
 104.5  97.3 104.3]
--------------------------------------------------------------------------------------------

In [6]:
del df["index"]

In [7]:
df.duplicated().value_counts()

False    60
True      1
dtype: int64

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df[df.price.isnull()]

company body-style  wheel-base  length engine-type num-of-cylinders  \
22    isuzu      sedan        94.5   155.9         ohc             four   
47  porsche  hatchback        98.4   175.7       dohcv            eight   

    horsepower  average-mileage  price  
22          70               38    NaN  
47         288               17    NaN

In [10]:
df[(df["company"] == "isuzu") & (df["body-style"] == "sedan")]

company body-style  wheel-base  length engine-type num-of-cylinders  \
21   isuzu      sedan        94.3   170.7         ohc             four   
22   isuzu      sedan        94.5   155.9         ohc             four   

    horsepower  average-mileage   price  
21          78               24  6785.0  
22          70               38     NaN

In [63]:
df[(df["company"] == "porsche") & (df["body-style"] == "hatchback")]

company body-style  wheel-base  length engine-type num-of-cylinders  \
47  porsche  hatchback        98.4   175.7       dohcv            eight   

    horsepower  average-mileage  price  
47         288               17    NaN

In [65]:
df[df["company"] == "porsche"]

company   body-style  wheel-base  length engine-type num-of-cylinders  \
45  porsche      hardtop        89.5   168.9        ohcf              six   
46  porsche  convertible        89.5   168.9        ohcf              six   
47  porsche    hatchback        98.4   175.7       dohcv            eight   

    horsepower  average-mileage    price  
45         207               17  34028.0  
46         207               17  37028.0  
47         288               17      NaN

In [19]:
df.dropna(inplace=True)

In [20]:
df[df.isnull()].value_counts()

Series([], dtype: int64)

In [74]:
df.to_csv("Automobile_data_2.csv")

##### Exercise 3: Find the most expensive car company name

In [75]:
df.head()

company   body-style  wheel-base  length engine-type num-of-cylinders  \
0  alfa-romero  convertible        88.6   168.8        dohc             four   
1  alfa-romero  convertible        88.6   168.8        dohc             four   
2  alfa-romero    hatchback        94.5   171.2        ohcv              six   
3         audi        sedan        99.8   176.6         ohc             four   
4         audi        sedan        99.4   176.6         ohc             five   

   horsepower  average-mileage    price  
0         111               21  13495.0  
1         111               21  16500.0  
2         154               19  16500.0  
3         102               24  13950.0  
4         115               18  17450.0

In [22]:
df.sort_values(by="price", ascending=False)[["company", "price"]].head(1)

company    price
35  mercedes-benz  45400.0

In [21]:
df.sort_values(by="price", ascending=False)[["company", "price"]].tail(1)

company   price
13  chevrolet  5151.0

##### Exercise 4: Print All Toyota Cars details

In [103]:
df[df.company == "toyota"]

company body-style  wheel-base  length engine-type num-of-cylinders  \
48  toyota  hatchback        95.7   158.7         ohc             four   
49  toyota  hatchback        95.7   158.7         ohc             four   
50  toyota  hatchback        95.7   158.7         ohc             four   
51  toyota      wagon        95.7   169.7         ohc             four   
52  toyota      wagon        95.7   169.7         ohc             four   
53  toyota      wagon        95.7   169.7         ohc             four   
54  toyota      wagon       104.5   187.8        dohc              six   

    horsepower  average-mileage    price  
48          62               35   5348.0  
49          62               31   6338.0  
50          62               31   6488.0  
51          62               31   6918.0  
52          62               27   7898.0  
53          62               27   8778.0  
54         156               19  15750.0

##### Exercise 5: Count total cars per company

In [105]:
df.company.value_counts()

toyota           7
bmw              6
mazda            5
nissan           5
audi             4
mercedes-benz    4
mitsubishi       4
volkswagen       4
alfa-romero      3
chevrolet        3
honda            3
jaguar           3
dodge            2
porsche          2
volvo            2
isuzu            1
Name: company, dtype: int64

##### Exercise 6: Find each company’s Higesht price car

In [28]:
df.groupby("company")["price"].max().to_frame()

price
company               
alfa-romero    16500.0
audi           18920.0
bmw            41315.0
chevrolet       6575.0
dodge           6377.0
honda          12945.0
isuzu           6785.0
jaguar         36000.0
mazda          18344.0
mercedes-benz  45400.0
mitsubishi      8189.0
nissan         13499.0
porsche        37028.0
toyota         15750.0
volkswagen      9995.0
volvo          13415.0

##### Exercise 7: Find the average mileage of each car making company

In [109]:
df.head(3)

company   body-style  wheel-base  length engine-type num-of-cylinders  \
0  alfa-romero  convertible        88.6   168.8        dohc             four   
1  alfa-romero  convertible        88.6   168.8        dohc             four   
2  alfa-romero    hatchback        94.5   171.2        ohcv              six   

   horsepower  average-mileage    price  
0         111               21  13495.0  
1         111               21  16500.0  
2         154               19  16500.0

In [30]:
df.groupby("company")["average-mileage"].mean().to_frame()

average-mileage
company                       
alfa-romero          20.333333
audi                 20.000000
bmw                  19.000000
chevrolet            41.000000
dodge                31.000000
honda                26.333333
isuzu                24.000000
jaguar               14.333333
mazda                28.000000
mercedes-benz        18.000000
mitsubishi           29.500000
nissan               31.400000
porsche              17.000000
toyota               28.714286
volkswagen           31.750000
volvo                23.000000

##### Exercise 8: Sort all cars by Price column

In [115]:
df.sort_values(by="price", ascending=False).head()

company   body-style  wheel-base  length engine-type  \
35  mercedes-benz      hardtop       112.0   199.2        ohcv   
11            bmw        sedan       103.5   193.8         ohc   
34  mercedes-benz        sedan       120.9   208.1        ohcv   
46        porsche  convertible        89.5   168.9        ohcf   
12            bmw        sedan       110.0   197.0         ohc   

   num-of-cylinders  horsepower  average-mileage    price  
35            eight         184               14  45400.0  
11              six         182               16  41315.0  
34            eight         184               14  40960.0  
46              six         207               17  37028.0  
12              six         182               15  36880.0

##### Exercise 9: Concatenate two data frames using the following conditions
##### Create two data frames using the following two dictionaries.
GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]}                                   
japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}

In [32]:
GermanCars = {"Company" : ["Ford", "Mercedes", "BMV", "Audi"],
              "Price" : [23845, 171995, 135925, 71400]}

JapaneseCars = {"Company": ["Toyota", "Honda", "Nissan", "Mitsubishi"],
                "Price" : [29995, 23600, 61500, 58900]}

In [33]:
GermanCars = pd.DataFrame(GermanCars)
GermanCars

Company   Price
0      Ford   23845
1  Mercedes  171995
2       BMV  135925
3      Audi   71400

In [34]:
JapaneseCars = pd.DataFrame(JapaneseCars)
JapaneseCars

Company  Price
0      Toyota  29995
1       Honda  23600
2      Nissan  61500
3  Mitsubishi  58900

In [36]:
pd.concat([GermanCars, JapaneseCars], keys=["Germany", "Japan"])

Company   Price
Germany 0        Ford   23845
        1    Mercedes  171995
        2         BMV  135925
        3        Audi   71400
Japan   0      Toyota   29995
        1       Honda   23600
        2      Nissan   61500
        3  Mitsubishi   58900

#####  Exercise 10: Merge two data frames using the following condition
##### Create two data frames using the following two Dicts, Merge two data frames, and append the second data frame as a new column to the first data frame.
Car_Price = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'Price': [23845, 17995, 135925 , 71400]}                               
car_Horsepower = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'], 'horsepower': [141, 80, 182 , 160]}

In [37]:
car_price = {
    "Company" : ["Toyota", "Honda", "BMV", "Audi"],
    "Price" : [23845, 17995, 135925, 71400]
}

car_horsepower = {
    "Company" : ["Toyota", "Honda", "BMV", "Audi"],
    "Horsepower" : [141, 80, 182, 16]
}

In [38]:
car_price = pd.DataFrame(car_price)
car_price

Company   Price
0  Toyota   23845
1   Honda   17995
2     BMV  135925
3    Audi   71400

In [39]:
car_horsepower = pd.DataFrame(car_horsepower)
car_horsepower

Company  Horsepower
0  Toyota         141
1   Honda          80
2     BMV         182
3    Audi          16

In [40]:
pd.merge(car_price, car_horsepower, on="Company")

Company   Price  Horsepower
0  Toyota   23845         141
1   Honda   17995          80
2     BMV  135925         182
3    Audi   71400          16